### ISSUE TITLE
Add product datetime

### ISSUE THREAD

**Issue by Timmy0618** [holo-otaku/dst-frontend#63]
add product default date is not created
![image](https://github.com/holo-otaku/dst-frontend/assets/68181703/67ec2597-7984-4279-864b-c49db998ea6c)
![image](https://github.com/holo-otaku/dst-frontend/assets/68181703/4ea84cbd-9c34-45ee-82a5-84c80fe5ffc8)

**Comment by hanshino** [comment]
使用者自己都不設定必填了，還要幫他塞預設?

**Comment by Timmy0618** [comment]
那留空好了，應該不用顯示才對
